### ISSUE TITLE
BigQuery connector

### ISSUE THREAD

**Issue by Jyrsa** [ellieapi/ellie-connectors#1]
Love the idea of syncing between Ellie and operational database. Do you have plans of implementing a BigQuery connector?

**Comment by ghost** [comment]
Hi! Currently we have no official plans for BigQuery, but that isn't to say one wouldn't be made sometime in the future. We're also working with our consultant & technology partners on various customer cases, which might result in additional solutions being published here. So, in short, no - or not yet at least :)
